### PR TITLE
[backplane-2.4]: 🐛 upgrade addondeploymentconfigs to include proxy ca bundle (#299)

### PR DESCRIPTION
**Pull request by elgnay**
## Related issue(s)

https://issues.redhat.com/browse/ACM-8382

### CODE REVIEW

**Comment by elgnay** [comment]
@Kyl-Bempah Could you please help to check why `Red Hat Trusted App Test / mce-24-pvl7l / tektok-runner-enterprise-contract-mce-2.4 ` is failed? I cannot see any log or error message. By the way, since the job is not required, can I just ignore it and merge the change?

**Comment by Kyl-Bempah** [comment]
> @Kyl-Bempah Could you please help to check why `Red Hat Trusted App Test / mce-24-pvl7l / tektok-runner-enterprise-contract-mce-2.4 ` is failed? I cannot see any log or error message. By the way, since the job is not required, can I just ignore it and merge the change?

Yes for now feel free to ignore the mce-2.4 build and focus on the others

**Comment by elgnay** [comment]
/override Red Hat Trusted App Test / mce-24-pvl7l / tektok-runner-enterprise-contract-mce-2.4

**Pull request merged**
